// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Permission struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsSystem    bool           `json:"is_system"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID                 uuid.UUID      `json:"id"`
	WorkspaceID        uuid.UUID      `json:"workspace_id"`
	Name               string         `json:"name"`
	Email              string         `json:"email"`
	Password           sql.NullString `json:"password"`
	EmailVerified      bool           `json:"emailVerified"`
	Image              sql.NullString `json:"image"`
	CreatedAt          sql.NullTime   `json:"createdAt"`
	UpdatedAt          sql.NullTime   `json:"updatedAt"`
	RecoverToken       sql.NullString `json:"recover_token"`
	RecoverTokenExpiry sql.NullTime   `json:"recover_token_expiry"`
	ConfirmToken       sql.NullString `json:"confirm_token"`
	RoleID             uuid.NullUUID  `json:"role_id"`
}

type Workspace struct {
	ID        uuid.UUID             `json:"id"`
	Name      string                `json:"name"`
	CreatedAt sql.NullTime          `json:"created_at"`
	UpdatedAt sql.NullTime          `json:"updated_at"`
	Settings  pqtype.NullRawMessage `json:"settings"`
}
