// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID                 uuid.UUID      `json:"id"`
	WorkspaceID        uuid.UUID      `json:"workspace_id"`
	Role               string         `json:"role"`
	Name               string         `json:"name"`
	Email              string         `json:"email"`
	Password           sql.NullString `json:"password"`
	EmailVerified      bool           `json:"emailVerified"`
	Image              sql.NullString `json:"image"`
	CreatedAt          sql.NullTime   `json:"createdAt"`
	UpdatedAt          sql.NullTime   `json:"updatedAt"`
	RecoverToken       sql.NullString `json:"recover_token"`
	RecoverTokenExpiry sql.NullTime   `json:"recover_token_expiry"`
	ConfirmToken       sql.NullString `json:"confirm_token"`
}

type Workspace struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
