// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, name string) (Workspace, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
