// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (workspace_id, role, name, email, password, "emailVerified")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, role, name, email, password, "emailVerified", image, "createdAt", "updatedAt", recover_token, recover_token_expiry, confirm_token
`

type CreateUserParams struct {
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	Role          string         `json:"role"`
	Name          string         `json:"name"`
	Email         string         `json:"email"`
	Password      sql.NullString `json:"password"`
	EmailVerified bool           `json:"emailVerified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.WorkspaceID,
		arg.Role,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecoverToken,
		&i.RecoverTokenExpiry,
		&i.ConfirmToken,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWorkspace(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, workspace_id, role, name, email, password, "emailVerified", image, "createdAt", "updatedAt", recover_token, recover_token_expiry, confirm_token FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecoverToken,
		&i.RecoverTokenExpiry,
		&i.ConfirmToken,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, workspace_id, role, name, email, password, "emailVerified", image, "createdAt", "updatedAt", recover_token, recover_token_expiry, confirm_token FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecoverToken,
		&i.RecoverTokenExpiry,
		&i.ConfirmToken,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, created_at, updated_at FROM workspaces
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $2
WHERE id = $1
RETURNING id, workspace_id, role, name, email, password, "emailVerified", image, "createdAt", "updatedAt", recover_token, recover_token_expiry, confirm_token
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID      `json:"id"`
	Password sql.NullString `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecoverToken,
		&i.RecoverTokenExpiry,
		&i.ConfirmToken,
	)
	return i, err
}

const updateUserTokens = `-- name: UpdateUserTokens :one
UPDATE users 
SET recover_token = $2, recover_token_expiry = $3, confirm_token = $4
WHERE id = $1
RETURNING id, workspace_id, role, name, email, password, "emailVerified", image, "createdAt", "updatedAt", recover_token, recover_token_expiry, confirm_token
`

type UpdateUserTokensParams struct {
	ID                 uuid.UUID      `json:"id"`
	RecoverToken       sql.NullString `json:"recover_token"`
	RecoverTokenExpiry sql.NullTime   `json:"recover_token_expiry"`
	ConfirmToken       sql.NullString `json:"confirm_token"`
}

func (q *Queries) UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserTokens,
		arg.ID,
		arg.RecoverToken,
		arg.RecoverTokenExpiry,
		arg.ConfirmToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecoverToken,
		&i.RecoverTokenExpiry,
		&i.ConfirmToken,
	)
	return i, err
}
